server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/roomdb
    username: roomuser
    password: roompass
  kafka:
    bootstrap-servers: localhost:9092
  rabbitmq:
    host: localhost
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 100ms
    connect-timeout: 5000
    client-type: lettuce
    cluster:
      nodes:
        - localhost:6379
      max-redirects: 3
    sentinel:
      master: mymaster
      nodes:
        - localhost:26379
      password: null
    password: null