server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: useruser
    password: userpass
  kafka:
    bootstrap-servers: localhost:9092
  rabbitmq:
    host: localhost
  redis:
    host: localhost 